!$THEME = "xmos"

!if %not(%variable_exists("$BGCOLOR"))
!$BGCOLOR = "white"
!endif

skinparam backgroundColor $BGCOLOR
skinparam useBetaStyle false

!$X_DARKGREY = "#464749"
!$X_LIGHTGREY = "#D1D3D4"
!$X_BLUE = "#1399DB"
!$X_LIGHTBLUE = "#44BBF1"
!$X_DARKGREEN = "#99DA07"
!$X_LIGHTGREEN = "#B8E720"
!$X_TEAL = "#0B668F"
!$X_MUSTARD = "#E7B320"
!$X_AUBERGINE = "#8F0B65"
!$X_DEEPPURPLE = "#4807DA"
!$X_TERRACOTTA = "#E0691F"
!$X_OAKGREEN = "#66800B"
!$X_TEAMSPIRITED = "#3413DB"
!$X_GREATPLACETOWORK = "#9813DB"
!$X_ADAPTABLEANDINNOVATIVE = "#DB1399"
!$X_PROUDBUTHUMBLE = "#DB5513"
!$X_CUSTOMERFIRST = "#4464F1"

!$WHITE = "#FFFFFF"
!$BLACK = "#000000"

!$FGCOLOR = $DARK
!$PRIMARY = $X_DARKGREY
!$PRIMARY_LIGHT = $X_LIGHTGREY
!$PRIMARY_DARK = $X_DARKGREY
!$PRIMARY_TEXT = $X_DARKGREY
!$SECONDARY = $X_BLUE
!$SECONDARY_LIGHT = $X_LIGHTBLUE
!$SECONDARY_DARK = $X_BLUE
!$SECONDARY_TEXT = $X_LIGHTGREY
!$INFO = $X_DARKGREEN
!$INFO_LIGHT = $X_LIGHTGREEN
!$INFO_DARK = $X_DARKGREEN
!$INFO_TEXT = $X_LIGHTGREY
!$SUCCESS = "#339933"
!$SUCCESS_LIGHT = "#5cad5c"
!$SUCCESS_DARK = "#297a29"
!$SUCCESS_TEXT = $WHITE
!$WARNING = "#ffae42"
!$WARNING_LIGHT = "#ffbe68"
!$WARNING_DARK = "#cc8b35"
!$WARNING_TEXT = $WHITE
!$DANGER = "#ff3333"
!$DANGER_LIGHT = "#ff5c5c"
!$DANGER_DARK = "#cc2929"
!$DANGER_TEXT = $WHITE

!procedure $success($msg)
  <font color=$SUCCESS><b>$msg
!endprocedure

!procedure $failure($msg)
  <font color=$DANGER><b>$msg
!endprocedure

!procedure $warning($msg)
  <font color=$WARNING><b>$msg
!endprocedure

!procedure $primary_scheme()
    FontColor $PRIMARY_TEXT
    BorderColor $PRIMARY_LIGHT
    BackgroundColor $PRIMARY_LIGHT
!endprocedure
''
'' Style settings
''
<style>
  root {
    BackgroundColor $BGCOLOR
    FontColor $PRIMARY_TEXT
    HyperLinkColor $X_BLUE
    LineColor $PRIMARY_DARK
    LineThickness 1
    Margin 10
    Padding 6
    Shadowing 0.0
  }
  node {
   Padding 15
   roundcorner 20
   BackgroundColor $PRIMARY
  }
  caption {
    LineThickness 0
  }
  footer {
    LineThickness 0
  }
  groupHeader {
    BackgroundColor $SECONDARY
    FontColor $INFO
    FontStyle bold
  }
  header {
    LineThickness 0
  }
  referenceHeader {
    BackgroundColor $BGCOLOR
    FontColor $DARK
    FontStyle bold
  }
  separator {
    BackgroundColor $FGCOLOR
    FontColor $BGCOLOR
    FontStyle bold
  }
  nwdiagDiagram {
    network {
        $primary_scheme()    
        LineColor $PRIMARY
        LineThickness 1.0
        FontColor $PRIMARY_DARK
    }
    server {
        $primary_scheme()
    }
    arrow {
        FontColor $PRIMARY_DARK
        LineColor $PRIMARY_DARK
    }
    group {
        BackGroundColor $LIGHT
        LineColor $LIGHT_DARK
        LineThickness 2.0
        Margin 5
        Padding 5
    }
  }
  ganttDiagram {
    task {
        $primary_scheme()
        LineColor $PRIMARY
        Margin 10
        Padding 6
    }
    note {
        FontColor $INFO_TEXT
        LineColor $INFO_DARK
        BackGroundColor $INFO
    }
    separator {
        LineColor $SECONDARY
        BackGroundColor $SECONDARY-$SECONDARY_DARK
        FontColor $SECONDARY_TEXT
    }
    milestone {
        FontColor $INFO
        FontSize 16
        FontStyle italic
        BackGroundColor $SECONDARY
        LineColor $SECONDARY_DARK
    }
    timeline {
        BackgroundColor $SECONDARY
        FontColor $SECONDARY_TEXT
    }
    closed {
        BackgroundColor $WARNING_DARK
        FontColor $WARNING_TEXT
    }
  }
</style>
''
'' Global Default Values
''
skinparam defaultFontName        "Arial Nova Light"
skinparam defaultFontSize        12
skinparam dpi                    300
skinparam shadowing              false
skinparam roundcorner            20
skinparam ParticipantPadding     30
skinparam BoxPadding             30
skinparam Padding                10
skinparam ArrowColor             $X_LIGHTGREEN
skinparam stereotype {
    CBackgroundColor $SECONDARY_LIGHT
    CBorderColor $SECONDARY_DARK
    ABackgroundColor $SUCCESS_LIGHT
    ABorderColor $SUCCESS_DARK
    IBackgroundColor $DANGER_LIGHT
    IBorderColor $DANGER_DARK
    EBackgroundColor $WARNING_LIGHT
    EBorderColor $WARNING_DARK
    NBackgroundColor $INFO_LIGHT
    NBorderColor $INFO_DARK
}
skinparam title {
    FontColor                    $X_DARKGREY
    BorderColor                  $X_LIGHTGREY
    FontSize                     16
    BorderRoundCorner            8
    BorderThickness              1
    BackgroundColor              $X_DARKGREEN
}


skinparam legend {
    BackgroundColor $PRIMARY
    BorderColor $PRIMARY_DARK
    FontColor $PRIMARY_TEXT
}

!startsub swimlane
skinparam swimlane {
    BorderColor $INFO
    BorderThickness 2
    TitleBackgroundColor  $SECONDARY_LIGHT-$SECONDARY
    TitleFontColor $PRIMARY
}
!endsub

!startsub activity

skinparam activity {
    $primary_scheme()
    BarColor $SUCCESS
    StartColor $INFO
    EndColor $INFO
    DiamondBackgroundColor $SECONDARY-$SECONDARY_DARK
      DiamondBorderColor $SECONDARY_DARK
    DiamondFontColor $SECONDARY_TEXT
}
!endsub

!startsub participant

skinparam participant {
    $primary_scheme()
    ParticipantBorderThickness 2
}
!endsub

!startsub actor

skinparam actor {
    $primary_scheme()
    BackgroundColor $X_LIGHTGREEN
    BorderColor $X_LIGHTGREEN
}
!endsub

!startsub arrow

skinparam arrow {
    Thickness 1
    Color $PRIMARY_DARK
    FontColor $FGCOLOR
}
!endsub

!startsub sequence

skinparam sequence {
    BorderColor $PRIMARY
    ' For some reason sequence title font color does not pick up from global
    TitleFontColor $SECONDARY_TEXT
    BackgroundColor $BGCOLOR
    StartColor $PRIMARY
    EndColor $PRIMARY
    ''
    BoxBackgroundColor $X_BLUE
    BoxBorderColor $GRAY
    BoxFontColor $DARK
    ''
    ArrowFontColor $X_DARKGREY
    ''
    DelayFontColor $DARK
    ''
    LifeLineBorderColor $SECONDARY_DARK
    LifeLineBorderThickness 2
    LifeLineBackgroundColor $SECONDARY_LIGHT
    ''
    GroupBorderColor $SECONDARY_DARK
    GroupFontColor $X_DARKGREY
    GroupHeaderFontColor $WHITE
    GroupHeaderFontStyle "Normal"
    ''
    DividerBackgroundColor $X_DARKGREEN
    DividerBorderColor $GRAY
    DividerBorderThickness 2
    DividerFontColor $X_DARKGREY
    DividerFontStyle "Normal"
    ''
    ParticipantBackgroundColor $X_BLUE
    ParticipantFontColor $WHITE
    ''
    ReferenceBackgroundColor $BGCOLOR
    ReferenceBorderColor $GRAY
    ReferenceFontColor $DARK
    ReferenceHeaderFontColor $INFO
    ''
    StereotypeFontColor $PRIMARY_TEXT
}
!endsub

!startsub partition

skinparam partition {
    BorderColor $PRIMARY
    FontColor $PRIMARY_DARK
    BackgroundColor $BGCOLOR
}
!endsub

!startsub collections

skinparam collections {
    $primary_scheme()
}
!endsub

!startsub control

skinparam control {
    $primary_scheme()
}
!endsub

!startsub entity

skinparam entity {
    $primary_scheme()
}
!endsub

!startsub boundary

skinparam boundary {
    $primary_scheme()
    BackgroundColor $X_LIGHTGREEN
    BorderColor $X_DARKGREEN
}
!endsub

!startsub agent

skinparam agent {
    BackgroundColor #orange
    BorderColor $X_LIGHTGREEN
    FontColor #333333
}
!endsub

!startsub note

skinparam note {
    BorderThickness 1
    BackgroundColor $INFO_LIGHT
    BorderColor $INFO
    FontColor $X_DARKGREY
}
!endsub

!startsub artifact

skinparam artifact {
    BackgroundColor white-$LIGHT
    BorderColor $SECONDARY_DARK
    FontColor $SECONDARY_DARK
}
!endsub

!startsub component

skinparam component {
    $primary_scheme()
}
!endsub

!startsub interface

skinparam interface {
    BackgroundColor  $DANGER_LIGHT
    BorderColor  $DANGER
    FontColor $DARK
}
!endsub

!startsub storage

skinparam storage {
    BackgroundColor $WARNING_LIGHT-$WARNING
      BorderColor $WARNING
    FontColor $WARNING_TEXT
}
!endsub

!startsub node

skinparam node {
    BackgroundColor $BGCOLOR
    BorderColor $PRIMARY_LIGHT
    FontColor $PRIMARY_TEXT
}
!endsub

!startsub cloud

skinparam cloud {
    BackgroundColor #F2FCFE-#eeeeee
    BorderColor $F2FCFE
    FontColor $PRIMARY_TEXT
}
!endsub

!startsub database

skinparam database {
    $primary_scheme()
    BackgroundColor  $BGCOLOR
}
!endsub

!startsub class

skinparam class {
    $primary_scheme()
    HeaderBackgroundColor $PRIMARY_LIGHT
    StereotypeFontColor $DARK
    StereotypeFontSize 9
    BorderThickness 1
    AttributeFontColor $DARK
    AttributeFontSize 11
}
!endsub

!startsub object

skinparam object {
    $primary_scheme()
    StereotypeFontColor $LIGHT
    BorderThickness 1
    AttributeFontColor $DARK
    AttributeFontSize 11
}
!endsub

!startsub usecase

skinparam usecase {
    $primary_scheme()
    BorderThickness 1
    BorderColor $X_LIGHTBLUE
    BackgroundColor $X_LIGHTBLUE
    StereotypeFontColor $PRIMARY
}
!endsub

!startsub rectangle

skinparam rectangle {
    $primary_scheme()
    BackgroundColor $BGCOLOR
    BorderThickness 1
    FontColor $PRIMARY_DARK
    FontStyle Normal
    StereotypeFontColor $PRIMARY_LIGHT
}
!endsub

!startsub package

skinparam package {
    $primary_scheme()
    BackgroundColor $WHITE
    BorderColor $PRIMARY_DARK
    BorderThickness 2
}
!endsub

!startsub folder

skinparam folder {
    BackgroundColor $PRIMARY_LIGHT
      BorderColor $WARNING
    FontColor $WARNING
    BorderThickness 2
}
!endsub

!startsub frame

skinparam frame {
    BackgroundColor $PRIMARY_LIGHT
      BorderColor $INFO
    FontColor $INFO
    BorderThickness 2
}
!endsub

!startsub state

skinparam state {
    $primary_scheme()
    BorderColor $PRIMARY_DARK
    StartColor $INFO
    EndColor $INFO
    AttributeFontColor $SECONDARY_TEXT
    AttributeFontSize 11
}
!endsub

!startsub queue

skinparam queue {
    $primary_scheme()
}
!endsub

!startsub card

skinparam card {
    BackgroundColor $INFO_LIGHT-$INFO
    BorderColor $INFO
    FontColor $INFO_TEXT
}
!endsub

!startsub file

skinparam file {
    BackgroundColor $SECONDARY_LIGHT-$SECONDARY
    BorderColor $SECONDARY_DARK
    FontColor $SECONDARY_TEXT

}
!endsub

!startsub stack

skinparam stack {
    $primary_scheme()
}
!endsub
